config/routes.rb
Rails.application.routes.draw do
  filter :client

  root 'welcome#index'

  get 'example', to: 'welcome#example', as: 'example'

  resources :leagues do
    get 'admin'
    get 'admin/:user_id/toggle', to: 'leagues#create_admin', as: 'admin_toggle'

    get 'players'

    resources :invites, only: [:new, :create]
    get 'invite/generate', to: 'invites#generate', as: 'generate_invite'
    get 'join/:token', to: 'invites#join', as: 'join'
    post 'invite/friend', to: 'invites#friend'

    resources :seasons do
      resources :games, only: [:show, :create]
    end

#    resources :tournaments, only: [:index]
  end

  get 'invite', to: 'invites#general_new', as: 'invite'

  get 'games/new', to: 'games#new', as: 'new_game'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update] do
    resources :avatar, only: [:show]
    post 'avatar', to: 'avatars#create', as: 'avatar_create'
  end

  get 'gods', to: 'gods#index', as: 'god'

  get 'ratings/leagues', to: 'ratings#leagues', as: 'league_ratings'
  get 'ratings/seasons', to: 'ratings#seasons', as: 'season_ratings'
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  include Tokenable

  belongs_to :league
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!, except: [:join]
  before_action :load_menu, except: [:join]
  before_action :load_leagues, only: [:new, :general_new]
  before_action :load_friends, only: [:new, :general_new]

  def new
    @league = @leagues.find params[:league_id]
  end

  def general_new
  end

  def generate
    league = current_user.leagues.find params[:league_id]
    invite = Invite.create league: league
    invite_path = league_join_url league, invite.token
    render json: { invite_path: invite_path, league_name: league.name }
  end

  def create
    email = params[:invite][:email]
    league = current_user.leagues.find params[:league_id]
    invite = Invite.create league: league
    InviteMailer.invite_email(current_user, email, league, invite.token).deliver_now
    render nothing: true
  end

  def friend
    user = User.find params[:invite][:id]
    league = current_user.leagues.find params[:league_id]
    invite = Invite.create league: league
    InviteMailer.invite_email(current_user, user.email, league, invite.token).deliver_now
    render nothing: true
  end

  def forward_user?
    if not user_signed_in?
      session['user_return_to'] = request.fullpath
      redirect_to url_for(new_user_session_path email: params[:email]), turbolinks: true
      true
    else
      false
    end
  end

  def join
    if not forward_user?
      invite = Invite.where(token: params[:token]).first
      league = invite.league
      if invite.nil?
        flash[:notice] = 'The token has expired'
        redirect_to url_for(root_path), turbolinks: true
      else
        if league.users.where(id: current_user).first != nil
          flash[:notice] = 'You are already a member of "' + league.name + '"'
          invite.destroy
          redirect_to url_for(league_path league), turbolinks: true
        else
          LeagueMembership.create user: current_user, league: league, admin: false
          LeagueRating.create user: current_user, league: league,
                              rating: LEAGUE_START,
                              games_played: 0, wins: 0, losses: 0
          invite.destroy
          league.seasons.each do |season|
            SeasonRating.create user: current_user, season: season,
                                rating: SEASON_START,
                                games_played: 0, wins: 0, losses: 0
          end
          if params[:new_user]
            redirect_to url_for(league_path league, new_user: true), turbolinks: true
          else
            redirect_to url_for(league_path league), turbolinks: true
          end
          invalidate_league_page league
        end
      end
    end
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_contact.html.erb
<center>
  <div id="invite_contacts" class="well"
       league_path="<%= url_for league_path(@league) %>"
       league_generate_invite_path="<%= url_for league_generate_invite_path(@league) %>">
    <div class="row">
      <div class="col-md-12">
        <label for="contacts_list">Choose Contacts From Phone</label>&nbsp;
        <ul id="contacts_list" class="list-group">
        </ul>
        <% if params[:new_league] %>
          <%= render 'invites/new_blurb' %>
        <% end %>
        <div class="btn-group btn-group-lg">
          <% if params[:new_league] %>
            <%= link_to league_path(@league) do %>
              <button class="btn btn-default">Skip</button>
            <% end %>
          <% end %>
          <button id="send_contact_invites" class="btn btn-success" type="button">
            Send Invites
          </button>
        </div>
      </div>
    </div>
  </div>
</center>

app/views/invites/_email.html.erb
<center>
  <div class="well">
    <div id="email_alert" class="invite_alert alert alert-danger" role="alert">
      An email address must be entered
    </div>
    <div class="form-group">
      <label for="email_address">Emails <i>(separated by commas)</i></label>
      <input type="email" id="email_address" class="form-control" autofocus>
    </div>
    <% if params[:new_league] %>
      <%= render 'invites/new_blurb' %>
    <% end %>
    <div class="btn-group btn-group-lg">
      <% if params[:new_league] %>
        <%= link_to league_path(@league) do %>
            <button class="btn btn-default">Skip</button>
        <% end %>
      <% end %>
      <button id="send_invite_button" type="button" class="btn btn-success">
        Send Invites
      </button>
    </div>
  </div>
</center>

app/views/invites/_friend.html.erb
<center>
  <div class="well">
    <div id="friend_alert" class="invite_alert alert alert-danger" role="alert">
      At least one friend must be selected
    </div>
    <div class="form-group">
      <label for="friend_list">Choose Contacts From Your Other Leagues</label>&nbsp;
      <ul id="friend_list" class="list-group">
        <% for friend in @friends %>
            <li class="friend list-group-item" friend_id="<%= friend.id %>">
                <%= friend.name %>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="create_friend_invite" class="btn btn-success">Send Invites</div>
  </div>
</center>

app/views/invites/_general_contact.html.erb
<center>
  <div id="invite_contacts" class="well" leagues_path="<%= url_for leagues_path %>">
    <div class="row">
      <div class="col-md-12">
        <div class="contact_league_alert invite_alert alert alert-danger"
             role="alert" hidden>
          A league must be selected
        </div>
        <div class="contact_number_alert invite_alert alert alert-danger"
             role="alert" hidden>
          At least one contact must be selected
        </div>
        <div class="form-group">
          <label for"contact_league_selector">League</label>
          <select id="contact_league_selector" class="form-control">
            <option value="">Select a league</option>
            <% for league in @leagues %>
              <option value="<%= league.id %>"><%= league.name %></option>
            <% end %>
          </select>
          <br>
          <label for="contacts_list">Choose Contacts From Phone</label>&nbsp;
          <ul id="contacts_list" class="list-group">
          </ul>
          <br>
          <div class="contact_league_alert invite_alert alert alert-danger"
               role="alert" hidden>
            A league must be selected
          </div>
          <div class="contact_number_alert invite_alert alert alert-danger"
               role="alert" hidden>
            At least one contact must be selected
          </div>
          <button id="send_general_contact_invites" class="btn btn-lg btn-success"
                  type="button">
            Send Invites
          </button>
        </div>
      </div>
    </div>
  </div>
</center>

app/views/invites/_general_email.html.erb
<center>
  <div class="well">
    <div id="league_alert" class="invite_alert alert alert-danger" role="alert">
      A league must be selected
    </div>
    <div id="email_alert" class="invite_alert alert alert-danger" role="alert">
      At least one email address must be entered
    </div>
    <div class="form-group">
      <label for"league_selector">League</label>
      <select id="league_selector" class="form-control">
        <option value="">Select a league</option>
        <% for league in @leagues %>
          <option value="<%= league.id %>"><%= league.name %></option>
        <% end %>
      </select>
      <label for="email_address">Emails <i>(separated by commas)</i></label>
      <input type="text" id="email_address" class="form-control" autofocus>
    </div>
    <div id="create_new_player_invite" class="btn btn-success">Send Invites</div>
  </div>
</center>

app/views/invites/_general_friend.html.erb
<center>
  <div class="well">
    <div id="friend_league_alert" class="invite_alert alert alert-danger" role="alert">
      A league must be selected
    </div>
    <div id="friend_alert" class="invite_alert alert alert-danger" role="alert">
      At least one friend must be selected
    </div>
    <div class="form-group">
      <label for"friend_league_selector">League</label>
      <select id="friend_league_selector" class="form-control">
        <option value="">Select a league</option>
        <% for league in @leagues %>
          <option value="<%= league.id %>"><%= league.name %></option>
        <% end %>
      </select>
      <label for="friend_list">Choose Contacts From Your Other Leagues</label>&nbsp;
      <ul id="friend_list" class="list-group">
        <% for friend in @friends %>
            <li class="friend list-group-item" friend_id="<%= friend.id %>">
                <%= friend.name %>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="create_general_friend_invite" class="btn btn-success">Send Invites</div>
  </div>
</center>

app/views/invites/_general_new.html.erb
<center>
  <div class="well">
    <div id="league_alert" class="invite_alert alert alert-danger" role="alert">
      A league must be selected
    </div>
    <div id="email_alert" class="invite_alert alert alert-danger" role="alert">
      At least one email address must be entered
    </div>
    <div class="form-group">
      <label for"league_selector">League</label>
      <select id="league_selector" class="form-control">
        <option value="">Select a league</option>
        <% for league in @leagues %>
          <option value="<%= league.id %>"><%= league.name %></option>
        <% end %>
      </select>
      <label for="email_address">Emails <i>(separated by commas)</i></label>
      <input type="text" id="email_address" class="form-control" autofocus>
    </div>
    <div id="create_new_player_invite" class="btn btn-success">Send Invites</div>
  </div>
</center>

app/views/invites/_nav_bar.html.erb
<ul class="nav nav-tabs">
  <% if show_contacts %>
    <li id="phone_contacts_button" role="presentation" class="active">
      <a>Phone Contacts</a>
    </li>
    <li id="email_button" role="presentation">
      <a>Email</a>
    </li>
  <% else %>
    <li id="email_button" role="presentation" class="active">
      <a>Email</a>
    </li>
  <% end %>
  <li id="friend_button" role="presentation">
    <a>Friend</a>
  </li>
</ul>

app/views/invites/_new.html.erb
<center>
  <div class="well">
    <div id="email_alert" class="invite_alert alert alert-danger" role="alert">
      An email address must be entered
    </div>
    <div class="form-group">
      <label for="email_address">Emails <i>(separated by commas)</i></label>
      <input type="email" id="email_address" class="form-control" autofocus>
    </div>
    <% if params[:new_league] %>
      <%= render 'invites/new_blurb' %>
    <% end %>
    <div class="btn-group btn-group-lg">
      <% if params[:new_league] %>
        <%= link_to 'Skip', league_path(@league), class: 'btn btn-default' %>
      <% end %>
      <button id="send_invite_button" type="button" class="btn btn-success">
        Send Invites
      </button>
    </div>
  </div>
</center>

app/views/invites/_new_blurb.html.erb
<div class="alert alert-danger" role="alert">
  Note: You can add more players later by clicking the 
  "<span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp;
  Invite Players" button in the side bar opened by clicking
  <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
  in the top left.
</div>

app/views/invites/contacts.html.erb
<div id="invite_contacts"
     league_path="<%= url_for league_path(@league) %>"
     league_generate_invite_path="<%= url_for league_generate_invite_path(@league) %>">
  <center>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>
          Invite contacts to <%= link_to @league.name, league_path(@league) %>
        </h1>
      </div>
      <div class="panel-body">
        <div id="selected_contacts" class="alert alert-success" role="alert">
          <h3>Selected Contacts</h3>
          <ul id="selected_contact_list" class="list-group"></ul>
        </div>
        <div class="row">
          <button id="send_contact_invites" class="btn btn-lg btn-success" type="button">
            Send Invites
          </button>
        </div>
        <br>
        <div class="form-group">
          <label for="contact_list">Add Contact From Phone</label>&nbsp;
          <select id="contact_list" class="form-control">
            <option value="">Select a contact...</option>
          </select>
        </div>
      </div>
    </div>
  </center>
  <% if params[:client] == 'and' %>
    <script>
      $(document).ready(android_ready);
    </script>
  <% end %>
</div>

app/views/invites/general_new.html.erb
<div id="invite_page" leagues_path="<%= url_for leagues_path %>">
  <% if params[:client] == 'and' %>
    <%= render partial: 'invites/nav_bar', locals: { show_contacts: true } %>
    <div id="contact_invites_pane">
      <%= render 'invites/general_contact' %>
    </div>
    <div id="email_invites_pane" hidden>
      <%= render 'invites/general_email' %>
    </div>
    <div id="friend_invites_pane" hidden>
      <%= render 'invites/general_friend' %>
    </div>
    <script>
      $(document).ready(android_ready);
    </script>
  <% else %>
    <% if params[:client] == 'ios' %>
      <%= render partial: 'invites/nav_bar', locals: { show_contacts: true } %>
      <div id="contact_invites_pane">
        <%= render 'invites/general_contact' %>
      </div>
      <div id="email_invites_pane" hidden>
        <%= render 'invites/general_email' %>
      </div>
      <div id="friend_invites_pane" hidden>
        <%= render 'invites/general_friend' %>
      </div>
      <script>
        $(document).ready(ios_ready);
      </script>
    <% else %>
      <%= render partial: 'invites/nav_bar', locals: { show_contacts: false } %>
      <div id="email_invites_pane">
        <%= render 'invites/general_email' %>
      </div>
      <div id="friend_invites_pane" hidden>
        <%= render 'invites/general_friend' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/invites/new.html.erb
<div id="invite_page" league_path="<%= url_for league_path(@league) %>">
  <% if params[:client] == 'and' %>
    <%= render partial: 'invites/nav_bar', locals: { show_contacts: true } %>
    <div id="contact_invites_pane">
      <%= render 'invites/contact' %>
    </div>
    <div id="email_invites_pane" hidden>
      <%= render 'invites/email' %>
    </div>
    <div id="friend_invites_pane" hidden>
      <%= render 'invites/friend' %>
    </div>
    <script>
      $(document).ready(android_ready);
    </script>
  <% else %>
    <% if params[:client] == 'ios' %>
      <%= render partial: 'invites/nav_bar', locals: { show_contacts: true } %>
      <div id="contact_invites_pane">
        <%= render 'invites/contact' %>
      </div>
      <div id="email_invites_pane" hidden>
        <%= render 'invites/email' %>
      </div>
      <div id="friend_invites_pane" hidden>
        <%= render 'invites/friend' %>
      </div>
      <script>
        $(document).ready(ios_ready);
      </script>
    <% else %>
      <%= render partial: 'invites/nav_bar', locals: { show_contacts: false } %>
      <div id="email_invites_pane">
        <%= render 'invites/email' %>
      </div>
      <div id="friend_invites_pane" hidden>
        <%= render 'invites/friend' %>
      </div>
    <% end %>
  <% end %>
</div>