config/routes.rb
Rails.application.routes.draw do
  filter :client

  root 'welcome#index'

  get 'example', to: 'welcome#example', as: 'example'

  resources :leagues do
    get 'admin'
    get 'admin/:user_id/toggle', to: 'leagues#create_admin', as: 'admin_toggle'

    get 'players'

    resources :invites, only: [:new, :create]
    get 'invite/generate', to: 'invites#generate', as: 'generate_invite'
    get 'join/:token', to: 'invites#join', as: 'join'
    post 'invite/friend', to: 'invites#friend'

    resources :seasons do
      resources :games, only: [:show, :create]
    end

#    resources :tournaments, only: [:index]
  end

  get 'invite', to: 'invites#general_new', as: 'invite'

  get 'games/new', to: 'games#new', as: 'new_game'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update] do
    resources :avatar, only: [:show]
    post 'avatar', to: 'avatars#create', as: 'avatar_create'
  end

  get 'gods', to: 'gods#index', as: 'god'

  get 'ratings/leagues', to: 'ratings#leagues', as: 'league_ratings'
  get 'ratings/seasons', to: 'ratings#seasons', as: 'season_ratings'
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :user
  has_many :league_memberships, dependent: :destroy
  has_many :users, through: :league_memberships
  has_many :invites, dependent: :destroy
  has_many :seasons, dependent: :destroy
  has_many :games, through: :seasons
  has_many :league_ratings, dependent: :destroy

  def ratings
    inner = 'SELECT MAX(league_ratings.created_at) FROM league_ratings '
    inner = inner + 'WHERE league_ratings.user_id = users.id '
    inner = inner + 'AND league_ratings.league_id = ' + id.to_s
    users.joins(:league_ratings)
         .where('league_ratings.created_at = (' + inner + ')')
         .order('league_ratings.rating DESC')
         .select('users.name AS name, league_ratings.*')
  end

  def owner? other_user
    other_user == user
  end

  def user_ratings user
    user.leagues.joins(:league_ratings)
        .select('league_ratings.*')
        .where('league_ratings.user_id': user.id)
        .where('league_ratings.league_id': id)
        .order('league_ratings.created_at DESC')
  end

  def user_rating user
    user_ratings(user).first
  end

  def user_ranking user
    ratings.where('league_ratings.games_played > 0').each_with_index do |rating, i|
      if rating.user_id == user.id
        return i + 1
      end
    end
    'Benchwarmer'
  end

  def user_games user
    user.players.joins(:game).joins(game: :season).where('seasons.league_id': id)
  end

  def get_wins user
    user_games(user).where(team: 0).size
  end

  def get_losses user
    user_games(user).where(team: 1).size
  end

  def get_spread user
    get_wins(user).to_s + '/' + get_losses(user).to_s
  end

  def get_ratio user
    get_wins(user) - get_losses(user)
  end

  def rankings
    users
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_menu, except: [:create, :create_admin]
  before_action :load_leagues, only: [:index, :players]

  def index
  end

  def show
    @league = current_user.leagues.find params[:id]
    load_league_page @league
  end

  def new
    @league = League.new
  end

  def create
    league = League.create league_params
    LeagueMembership.create user: current_user, league: league, admin: true
    LeagueRating.create user: current_user, league: league,
                        rating: LEAGUE_START,
                        games_played: 0, wins: 0, losses: 0
    invalidate_menu_cache
    redirect_to url_for(new_league_invite_path league, new_league: true), turbolinks: true
  end

  def edit
    @league = current_user.leagues.find params[:id]
  end

  def update
    league = current_user.leagues.find params[:id]
    league.update_attributes league_params
    redirect_to url_for(league_path league), turbolinks: true
  end

  def destroy
    league = current_user.leagues.find params[:id]
    if current_user.admin? league
      if league.games.count == 0
        league.destroy
        flash[:notice] = 'League ' + league.name + ' successfully deleted.'
        redirect_to url_for(root_path), turbolinks: true
      else
        flash[:alert] = 'You cannot delete a league that has games.'
        redirect_to url_for(league_path league), turbolinks: true
      end
    else
      flash[:alert] = 'You do not have admin privledges for the league ' + league.name
      redirect_to url_for(league_path league), turbolinks: true
    end
  end

  def admin
    @league = current_user.leagues.find params[:league_id]
    @seasons = @league.seasons.order created_at: :desc
    @users = @league.users.order name: :asc
  end

  def create_admin
    league = League.find params[:league_id]
    new_admin = User.find params[:user_id]
    if current_user.admin? league and not league.owner? new_admin
      league_membership = LeagueMembership.where(user: new_admin,
                                                 league: league).first
      league_membership.admin = !league_membership.admin
      league_membership.save
      render nothing: true
    else
      render nothing: true, status: :unauthorized
    end
  end

  def players
    @league = @leagues.find params[:league_id]
    @users = @league.users.order name: :asc
  end

  protected

  def league_params
    params.require(:league).permit :name, :user_id
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<div id="league_name_alert" class="alert alert-danger" role="alert">
  The league must have a name.
</div>
<%= form_for @league, html: { id: 'league_form', class: 'form-group' } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>
  <%= f.submit 'Create', class: 'btn btn-success btn-lg' %>
<% end %>

app/views/leagues/_show.html.erb
<center>
  <div class="well">
    <h1><%= @league.name %></h1>
  </div>  
  <div class="row">
    <div class="col-md-6">
      <%= render 'ratings/league_players' %>
      <%= render 'ratings/league_benchwarmers' %>
    </div>
    <div class="col-md-6">
      <%= render 'ratings/season_standings' %>
    </div>
  </div>
</center>

app/views/leagues/admin.html.erb
<div id="admin_page">
  <center>
    <div class="well">
      <h1>
        <%= link_to @league.name, league_path(@league) %>
        Admin Page
      </h1>
      <div id="admin_edit_button">
        <%= link_to edit_league_path(@league) do %>
          <button class="btn btn-primary">
            <h4>
              <span class="glyphicon glyphicon-cog"></span>
            </h4>
          </button>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h2>Seasons</h2>
          </div>
          <div class="panel-body">
            <%= link_to new_league_season_path(@league) do %>
              <button class="btn btn-success btn-lg">
                Create A Season
              </button>
            <% end %>
            <br>
            <br>
            <%= render 'seasons/index' %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2>Members</h2>
          </div>
          <div class="panel-body">
            <%= render template: 'leagues/members' %>
          </div>
        </div>
      </div>
    </div>
  </center>
</div>

app/views/leagues/edit.html.erb
<div id="edit_league">
  <center>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>
          Edit League <%= link_to @league.name, league_path(@league) %>'s Information
        </h1>
      </div>
      <div class="panel-body">
        <% if @league.games.count == 0 %>
          <%= link_to league_path(@league), method: :delete do %>
            <button class="btn btn-lg btn-danger">
              Delete League
            </button>
          <% end %>
          <br>
          <br>
        <% end %>
        <%= render 'leagues/form' %>
      </div>
    </div>
  </center>
</div>

app/views/leagues/index.html.erb
<div id="league_index">
  <center>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Leagues</h1>
      </div>
      <div class="panel-body">
        <% if @leagues.size > 0 %>
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <td>Name</td>
                <td>Rating</td>
                <td>Games</td>
                <td>+/-</td>
              </tr>
            </thead>
            <tbody>
              <% for league in @leagues %>
                <tr class="league_row"
                    league_path="<%= url_for league_path(league) %>">
                  <td><%= league.name %></td>
                  <% rating = league.user_rating current_user %>
                  <td><%= rating.rating %></td>
                  <td><%= rating.games_played %></td>
                  <td><%= rating.wins %>/<%= rating.losses %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <%= link_to new_league_path do %>
            <button id="add_league_button" type="button" class="btn btn-success btn-lg">
              Create A League
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </center>
</div>

app/views/leagues/invite.html.erb
<% invite_button = render template: 'leagues/invite_button' %>
<%= render template: 'common/nav_bar', locals: { additional_buttons: invite_button } %>
<div id="invite_page">
  <center>
    <h2>Invite to <%= @league.name %></h2>
    <div id="email_alert" class="alert alert-danger" role="alert">
      An email address must be entered
    </div>
    <div class="form-group">
      <label for="email_address">Email</label>
      <input type="email" id="email_address" class="form-control">
    </div>
  </center>
</div>
<script>
  $('#email_alert').hide();
</script>

app/views/leagues/members.html.erb
<div id="league_members" league_admin_path="<%= url_for league_admin_path(@league) %>">
  <center>
    <%= link_to new_league_invite_path(@league) do %>
      <button id="add_member" type="button" class="btn btn-danger btn-lg">
        Add Members
      </button>
    <% end %>
    <br>
    <br>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Name</td>
          <td>Admin Privledges</td>
        </tr>
      </thead>
      <tbody>
        <% for user in @users %>
          <tr class="member_row" member_path="<%= user_path user %>">
            <td><%= user.name %> (<%= user.email %>)</td>
            <% if @league.owner? user %>
              <td><b>Commisioner</b></td>
            <% else %>
              <td>
                <% if user.admin? @league %>
                  <input class="admin_checkbox" type="checkbox"
                         checked="true" user_id="<%= user.id %>">
                <% else %>
                  <input class="admin_checkbox" type="checkbox" user_id="<%= user.id %>">
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </center>
</div>

app/views/leagues/new.html.erb
<div id="new_league">
  <center>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Create A League</h1>
      </div>
      <div class="panel-body">
        <%= render 'leagues/form' %>
      </div>
    </div>
  </center>
</div>

app/views/leagues/show.html.erb
<div id="ratings_container" users="<%= url_for root_path %>users" me="<%= current_user.id %>">
  <%= raw @league_page %>
</div>