config/routes.rb
Rails.application.routes.draw do
  filter :client

  root 'welcome#index'

  get 'example', to: 'welcome#example', as: 'example'

  resources :leagues do
    get 'admin'
    get 'admin/:user_id/toggle', to: 'leagues#create_admin', as: 'admin_toggle'

    get 'players'

    resources :invites, only: [:new, :create]
    get 'invite/generate', to: 'invites#generate', as: 'generate_invite'
    get 'join/:token', to: 'invites#join', as: 'join'
    post 'invite/friend', to: 'invites#friend'

    resources :seasons do
      resources :games, only: [:show, :create]
    end

#    resources :tournaments, only: [:index]
  end

  get 'invite', to: 'invites#general_new', as: 'invite'

  get 'games/new', to: 'games#new', as: 'new_game'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update] do
    resources :avatar, only: [:show]
    post 'avatar', to: 'avatars#create', as: 'avatar_create'
  end

  get 'gods', to: 'gods#index', as: 'god'

  get 'ratings/leagues', to: 'ratings#leagues', as: 'league_ratings'
  get 'ratings/seasons', to: 'ratings#seasons', as: 'season_ratings'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :god
  has_one :avatar
  has_many :league_memberships
  has_many :leagues, through: :league_memberships
  has_many :seasons, through: :leagues
  has_many :league_ratings
  has_many :season_ratings
  has_many :players
  has_many :games, through: :players

  after_create :send_welcome_email

  def send_welcome_email
    WelcomeMailer.welcome_email(self).deliver_now
  end

  def last_updated_league
    leagues.joins(:league_ratings).order('league_ratings.created_at DESC').first
  end

  def get_wins
    players.where(team: 0).size
  end

  def get_losses
    players.where(team: 1).size
  end

  def get_spread
    get_wins.to_s + '/' + get_losses.to_s
  end

  def get_ratio
    get_wins - get_losses
  end

  def admin? league
    league_memberships.where(league_id: league).first.admin
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  require 'uri'

  def create
    session['user_return_to'] ||= '/'
    uri = URI(session['user_return_to'])
    old_query = uri.query || ''
    new_query = URI.decode_www_form(old_query) << ["new_user", "true"]
    uri.query = URI.encode_www_form(new_query)
    session['user_return_to'] = url_for uri.to_s
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_menu

  def show
    @user = User.find params[:id]
    @user_leagues = @user.leagues
    @avatar = Avatar.new
    graph_data_key = @user.id.to_s + 'graph'
    @graph_data = REDIS.get graph_data_key
    if not @graph_data
      @user_seasons = @user.seasons
      @graph_data = render_to_string partial: 'users/graph_data'
      REDIS.set graph_data_key, @graph_data
      REDIS.expire graph_data_key, REDIS_GRAPH_TTL
    else
      puts "\033[32mREDIS CACHE: LOADED GRAPH DATA \"#{graph_data_key}\033[0m"
    end
    load_user_games @user
  end

  def edit
  end

  def update
    current_user.name = params[:user][:name]
    current_user.save
    redirect_to url_for(user_path current_user), turbolinks: true
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_acronym user
    user.split(' ').inject '' do |str, word|
      str = str + word[0]
    end
  end
end

app/views/users/_graph_data.html.erb
<script>
  var league_ratings_data = <%= raw render(template: 'ratings/leagues.json') %>; 
  var season_ratings_data = <%= raw render(template: 'ratings/seasons.json') %>; 
  $(document).ready(graphs_ready);
</script>

app/views/users/edit.html.erb
<div id="edit_user_page">
  <center>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Your Information</h1>
      </div>
      <div class="panel-body">
        <div id="edit_user_name_alert" class="alert alert-danger" role="alert" hidden>
          Your name cannot be empty
        </div>
        <div class="form-group">
          <%= form_for current_user, html: { id: 'edit_user_form' } do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, id: 'edit_user_name', class: 'form-control' %>
            <br>
            <%= f.submit 'Update', class: 'btn btn-lg btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </center>
</div>

app/views/users/graph.html.erb
<div id="user_rating_graph" class="well">
  <ul class="nav nav-tabs">
    <li id="league_ratings_button" role="presentation">
      <a>League Ratings</a>
    </li>
    <li id="season_ratings_button" role="presentation" class="active">
      <a>Season Ratings</a>
    </li>
  </ul>
  <div class="panel panel-default">
    <div class="player_changes panel-body">
      <div id="graphs_container" class="row">
        <div id="league_ratings_graph">
          <div id="league_graph_canvas"></div>
        </div>
        <div id="season_ratings_graph">
          <div id="season_graph_canvas"></div>
        </div>
      </div>
    </div>
  </div>
  <%= raw @graph_data %>
</div>

app/views/users/image.html.erb
<div id="user_avatar_display">
  <%= image_tag 'balls-default.jpg', alt: 'Balls', class: 'img-thumbnail' %>
</div>
<% if current_user == @user %>
  <div id="user_avatar_upload_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="user_image_upload_modal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">
              &times;
            </span>
          </button>
          <h2 class="modal-title">
            Save Avatar
          </h2>
        </div>
        <div class="modal-body">
          <div id="avatar_file_alert" class="alert alert-danger" role="alert">
            No image file chosen.
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="user_avatar">Image</label>
                <input type="file" id="user_avatar" class="form-control">
              </div>
            </div>
            <div class="col-md-6">
              <form id="user_avatar_form">
                <%= image_tag 'balls-default.jpg', alt: 'Balls',
                              id: 'new_avatar', class: 'img-thumbnail' %>
              </form>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id="save_avatar_button" type="button" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>
  <script>
    $('#avatar_file_alert').hide();
    $('#user_avatar_display').click(function () {
      $('#user_avatar_upload_modal').modal('show');
    });
    function avatar_input (input) {
      if(input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (event_object) {
          $('#new_avatar').attr('src', event_object.target.result);
        };
        reader.readAsDataURL(input.files[0]);
      }
    }
    $('#user_avatar').change(function () {
      $('#avatar_file_alert').hide();
      avatar_input(this);
    });
    function send_avatar (input) {
      if(input.files && input.files[0]) {
        alert('here');
        var reader = new FileReader();
        reader.onload = function (event_object) {
          var data = { avatar_file: event_object.target.result };
          $.post('<%= user_avatar_path @user %>', data, function () {
            $('#user_avatar_upload_modal').modal('hide');
          });
        };
        reader.readAsBinaryString(input.files[0]);
      } else {
        $('#avatar_file_alert').show();
      }
    }
    $('#save_avatar_button').click(function () {
      $('#avatar_file_alert').hide();
      send_avatar($('#user_avatar')[0]);
    });
  </script>
<% end %>

app/views/users/show.html.erb
<div id="user_page">
  <center>
    <div class="well">
      <h1><%= @user.name %></h1>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= render template: 'avatars/image' %>
        <br>
      </div>
      <div class="col-md-6">
        <div class="panel panel-success">
          <div class="panel-heading">
            <div class="btn-group btn-group-lg">
            <button id="last_rating_button" type="button" class="btn btn-default" aria-label="Last league" disabled>
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"\>
            </button>
            <button type="button" class="btn btn-default" aria-label="League" disabled>
              Rankings
            </button>
            <button id="next_rating_button" type="button" class="btn btn-default" aria-label="Next league">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"\>
            </button>
            </div>
          </div>
          <div id="leagues_panel" class="panel-body">
            <% @user_leagues.each_with_index do |league, i| %>
              <div id="rating<%= i %>" class="league_rating panel panel-default">
                <div class="panel-heading">
                  <h3><%= link_to league.name, league_path(league) %></h3>
                </div>
                <div class="panel-body">
                  <h3><%= league.user_ranking @user %></h3>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="player_changes panel-body bg-warning">
            <div class="col-md-6">
              <%= @user.get_spread %>
            </div>
            <div class="col-md-6">
              <%= format_ratio @user.get_ratio %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= render template: 'users/graph' %>
    <%= raw @user_games %>
  </center>
</div>