config/routes.rb
Rails.application.routes.draw do
  filter :client

  root 'welcome#index'

  get 'example', to: 'welcome#example', as: 'example'

  resources :leagues do
    get 'admin'
    get 'admin/:user_id/toggle', to: 'leagues#create_admin', as: 'admin_toggle'

    get 'players'

    resources :invites, only: [:new, :create]
    get 'invite/generate', to: 'invites#generate', as: 'generate_invite'
    get 'join/:token', to: 'invites#join', as: 'join'
    post 'invite/friend', to: 'invites#friend'

    resources :seasons do
      resources :games, only: [:show, :create]
    end

#    resources :tournaments, only: [:index]
  end

  get 'invite', to: 'invites#general_new', as: 'invite'

  get 'games/new', to: 'games#new', as: 'new_game'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:show, :edit, :update] do
    resources :avatar, only: [:show]
    post 'avatar', to: 'avatars#create', as: 'avatar_create'
  end

  get 'gods', to: 'gods#index', as: 'god'

  get 'ratings/leagues', to: 'ratings#leagues', as: 'league_ratings'
  get 'ratings/seasons', to: 'ratings#seasons', as: 'season_ratings'
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user

  mount_uploader :image, AvatarUploader
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :season
  has_many :players, dependent: :destroy

  def winners
    players.where team: 0
  end

  def losers
    players.where team: 1
  end
end

app/models/god.rb
class God < ActiveRecord::Base
  belongs_to :user
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  include Tokenable

  belongs_to :league
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :user
  has_many :league_memberships, dependent: :destroy
  has_many :users, through: :league_memberships
  has_many :invites, dependent: :destroy
  has_many :seasons, dependent: :destroy
  has_many :games, through: :seasons
  has_many :league_ratings, dependent: :destroy

  def ratings
    inner = 'SELECT MAX(league_ratings.created_at) FROM league_ratings '
    inner = inner + 'WHERE league_ratings.user_id = users.id '
    inner = inner + 'AND league_ratings.league_id = ' + id.to_s
    users.joins(:league_ratings)
         .where('league_ratings.created_at = (' + inner + ')')
         .order('league_ratings.rating DESC')
         .select('users.name AS name, league_ratings.*')
  end

  def owner? other_user
    other_user == user
  end

  def user_ratings user
    user.leagues.joins(:league_ratings)
        .select('league_ratings.*')
        .where('league_ratings.user_id': user.id)
        .where('league_ratings.league_id': id)
        .order('league_ratings.created_at DESC')
  end

  def user_rating user
    user_ratings(user).first
  end

  def user_ranking user
    ratings.where('league_ratings.games_played > 0').each_with_index do |rating, i|
      if rating.user_id == user.id
        return i + 1
      end
    end
    'Benchwarmer'
  end

  def user_games user
    user.players.joins(:game).joins(game: :season).where('seasons.league_id': id)
  end

  def get_wins user
    user_games(user).where(team: 0).size
  end

  def get_losses user
    user_games(user).where(team: 1).size
  end

  def get_spread user
    get_wins(user).to_s + '/' + get_losses(user).to_s
  end

  def get_ratio user
    get_wins(user) - get_losses(user)
  end

  def rankings
    users
  end
end

app/models/league_membership.rb
class LeagueMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/league_rating.rb
class LeagueRating < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :league
  has_many :games, dependent: :destroy
  has_many :season_ratings, dependent: :destroy

  def ratings
    inner = 'SELECT MAX(season_ratings.created_at) FROM season_ratings '
    inner = inner + 'WHERE season_ratings.user_id = users.id '
    inner = inner + 'AND season_ratings.season_id = ' + id.to_s
    league.users.joins(:season_ratings)
         .where('season_ratings.created_at = (' + inner + ')')
         .order('season_ratings.rating DESC')
         .select('users.name AS name, season_ratings.*')
  end

  def user_ratings user
    result = user.leagues.joins(seasons: :season_ratings)
                 .where('seasons.id': id)
                 .select('season_ratings.*')
                 .where('season_ratings.user_id': user.id)
                 .where('season_ratings.season_id': id)
                 .order('season_ratings.created_at DESC')
  end

  def user_rating user
    user_ratings(user).first
  end

  def user_games user
    user.players.joins(:game).where('games.season_id': id)
  end

  def get_wins user
    user_games(user).where(team: 0).size
  end

  def get_losses user
    user_games(user).where(team: 1).size
  end

  def get_spread user
    get_wins(user).to_s + '/' + get_losses(user).to_s
  end

  def get_ratio user
    get_wins(user) - get_losses(user)
  end
end

app/models/season_rating.rb
class SeasonRating < ActiveRecord::Base
  belongs_to :user
  belongs_to :season
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :god
  has_one :avatar
  has_many :league_memberships
  has_many :leagues, through: :league_memberships
  has_many :seasons, through: :leagues
  has_many :league_ratings
  has_many :season_ratings
  has_many :players
  has_many :games, through: :players

  after_create :send_welcome_email

  def send_welcome_email
    WelcomeMailer.welcome_email(self).deliver_now
  end

  def last_updated_league
    leagues.joins(:league_ratings).order('league_ratings.created_at DESC').first
  end

  def get_wins
    players.where(team: 0).size
  end

  def get_losses
    players.where(team: 1).size
  end

  def get_spread
    get_wins.to_s + '/' + get_losses.to_s
  end

  def get_ratio
    get_wins - get_losses
  end

  def admin? league
    league_memberships.where(league_id: league).first.admin
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_acronym user
    user.split(' ').inject '' do |str, word|
      str = str + word[0]
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/common/_head_tags.html.erb
<meta name="description" content="Create a ranked beer pong league for your friend circle, frat or sports team today!">
<meta name="keywords" content="ballsapp,beer pong,pong,tracker,beer pong tracker,beer pong rankings,beer pong league,beer pong app">
<meta name="robots" content="index,follow">
<meta name="DC.title" content="BallsApp">
<meta http-equiv="cleartype" content="on">
<meta name="MobileOptimized" content="320">
<meta name="HandheldFriendly" content="True">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<link rel="apple-touch-icon" href="<%= image_path 'touch-icon-iphone.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'touch-icon-ipad.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'touch-icon-iphone-retina.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'touch-icon-ipad-retina.png' %>">
<meta property="og:url" content="https://www.ballsapp.com">
<meta property="og:site_name" content="BallsApp">
<meta property="og:title" content="GET YOUR BALLS WET">
<meta property="og:description" content="Create a ranked beer pong league for your friend circle, frat or sports team today!">
<meta property="og:image" content="<%= image_path 'ballsapp.png' %>">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="600">
<meta property="og:image:height" content="600">
<meta property="twitter:site" content="BallsApp">
<meta property="twitter:creator" content="BallsApp">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:title" content="BallsApp">
<meta property="twitter:description" content="Create a ranked beer pong league for your friend circle, frat or sports team today!">
<meta property="twitter:image:src" content="<%= image_path 'ballsapp.png' %>">
<meta property="twitter:image:width" content="600">
<meta property="twitter:image:height" content="600">

app/views/common/_instructions.html.erb
<h4 class="instruction_step">Step 1:</h4>
<p class="underlined">
  Create a league
</p>
<p>
  A league consists of the people that you will be playing ranked games with (ex:
  Fraternity, Friend crew, etc.) and is a larger organizational unit than a season.
</p>
<h4 class="instruction_step">Step 2:</h4>
<p class="underlined">
  Create a season
</p>
<p>
  On the league admin page (opened with the
  "<span class="glyphicon glyphicon-king" aria-hidden="true"></span>" button on the side
  bar) you will see the option to create a season. A season has an end date and a defined
  set of rules (ex: 10 Cup Spring 2015). Multiple seasons can be running at one time.
  Everybody in a League is automatically enrolled in its seasons.
</p>
<h4 class="instruction_step">Step 3:</h4>
<p class="underlined">
  Invite your friends
</p>
<p>
  Invitations will be received via email and can be sent out by clicking
  “<span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp;Invite Players”
  on the side bar. If your friend has not created an account they will be asked to. To
  protect your privacy, the only people who can see a league are those who have been
  invited.
</p>
<h4 class="instruction_step">Step 4:</h4>
<p class="underlined">
  Log games
</p>
<p>
  The "<span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;Log Game"
  button can be found at the top of the side bar. The only way to determine the best
  player is to play so go put some balls in cups!
</p>

app/views/common/_menu.html.erb
<%= link_to user_path(current_user) do %>
  <header class="menu-header"
    <% if current_user.avatar.nil? %>
      style="background: url('<%= image_path 'ballsapp_logo_icon.jpg' %>') no-repeat 15px 15px;">
    <% else %>
      style="background: url('<%= current_user.avatar.image.icon.url %>') no-repeat 15px 15px;">
    <% end %>
    <span class="menu_header menu-header-title">
      <%= current_user.name %>
    </span>
    <%= link_to edit_user_path(current_user), class: 'edit_button' do %>
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    <% end %>
  </header>
<% end %>
<div id="home_button" class="menu_link">
  <%= link_to root_path do %>
    <header>
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      <span class="menu_label">Home</span>
    </header>
  <% end %>
</div>
<% if @all_seasons.size > 0 %>
  <div id="log_game_button" class="menu_link">
    <%= link_to new_game_path do %>
      <header>
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        <span class="menu_label">Log Game</span>
      </header>
    <% end %>
  </div>
<% end %>
<% if @leagues.size > 0 %>
  <div id="invite_player_button" class="menu_link">
    <%= link_to invite_path do %>
      <header>
        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
        <span class="menu_label">Invite Players</span>
      </header>
    <% end %>
  </div>
<% end %>
<% if current_user.god %>
  <div id="god_button" class="menu_link">
    <%= link_to god_path do %>
      <header>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="menu_label">God Page</span>
      </header>
    <% end %>
  </div>
<% end %>
<section class="menu-section">
  <div class="menu-section-title">
    <%= link_to leagues_path, class: 'menu_header' do %>
      Leagues
    <% end %>
    <%= link_to new_league_path, id: 'new_league_button' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    <% end %>
  </div>
  <% for league in @leagues %>
    <div class="league_menu_item">
      <%= link_to league.name, league_path(league) %>
      <% if current_user.admin? league %>
        <%= link_to league_admin_path(league), class: 'admin_menu_button' do %>
          <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</section>
<section id="sections_list" class="menu-section">
  <div class="menu_header menu-section-title">
    Seasons
  </div>
  <% for season in @all_seasons %>
    <div class="league_menu_item">
      <%= link_to season.name, league_season_path(season.league, season) %>
      <% if current_user.admin? season.league %>
        <%= link_to edit_league_season_path(season.league, season),
                    class: 'admin_menu_button' do %>
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</section>
<section id="instructions_button" class="menu_link">
  <a>
    <header>
      <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
      <span class="menu_label">Instructions</span>
    </header>
  </a>
</section>
<section id="sign_out_button" class="menu_link">
  <%= link_to destroy_user_session_path, method: :delete do %>
    <header>
      <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
      <span class="menu_label">Sign Out</span>
    </header>
  <% end %>
</section>

app/views/common/_new_user_blurb.html.erb
<div class="alert alert-danger" role="alert">
  <b></b> You can open this again later by pressing the
  "<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
  &nbsp;Instructions" button in the side bar opended by clicking
  <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
  in the top left.
</div>

app/views/common/google_adwords_sign_up.html.erb
<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 967820739;
    w.google_conversion_label = "WgbwCMDa6loQw4u_zQM";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    window.google_is_call = true;
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>

app/views/common/google_analytics.html.erb
<script>
  $(document).ready(function () {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-51916697-3', 'auto');
    ga('send', 'pageview');
  });
</script>

app/views/common/instruction_pane.html.erb
<div class="modal fade" id="instructions_modal" tabindex="-1" role="dialog"
     aria-labelledby="instructions_label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <center>
          <h4 class="modal-title" id="instructions_label">Instructions</h4>
        </center>
      </div>
      <div class="modal-body">
        <% if params[:new_user] %>
          <%= render 'common/new_user_blurb' %>
        <% end %>
        <%= render 'common/instructions' %>
        <% if params[:new_user] %>
          <%= render 'common/new_user_blurb' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% if params[:new_user] %>
  <script>
    $('#instructions_modal').modal();
  </script>
<% end %>

app/views/common/menu.html.erb
<%= link_to user_path(current_user) do %>
  <header class="menu-header"
    <% if current_user.avatar.nil? %>
      style="background: url('<%= image_path 'ballsapp_logo_icon.jpg' %>') no-repeat 15px 15px;">
    <% else %>
      style="background: url('<%= current_user.avatar.image.icon.url %>') no-repeat 15px 15px;">
    <% end %>
    <span class="menu-header-title">
      <%= current_user.name %>
    </span>
    <%= link_to edit_user_path(current_user), class: 'edit_button' do %>
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    <% end %>
  </header>
<% end %>
<% if @all_seasons.size > 0 %>
  <div id="log_game_button" class="menu_link">
    <%= link_to new_game_path do %>
      <header>
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        <span class="menu_label">Log game</span>
      </header>
    <% end %>
  </div>
<% end %>
<% if @leagues.size > 0 %>
  <div id="invite_player_button" class="menu_link">
    <%= link_to invite_path do %>
      <header>
        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
        <span class="menu_label">Invite Players</span>
      </header>
    <% end %>
  </div>
<% end %>
<% if current_user.god %>
  <div id="god_button" class="menu_link">
    <%= link_to god_path do %>
      <header>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="menu_label">God Page</span>
      </header>
    <% end %>
  </div>
<% end %>
<section class="menu-section">
  <div class="menu-section-title">
    <%= link_to leagues_path do %>
      Leagues
    <% end %>
    <%= link_to new_league_path, id: 'new_league_button' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    <% end %>
  </div>
  <% for league in @leagues %>
    <div class="league_menu_item">
      <%= link_to league.name, league_path(league) %>
      <% if current_user.admin? league %>
        <%= link_to league_admin_path(league), class: 'admin_menu_button' do %>
          <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</section>
<section id="sections_list" class="menu-section">
  <div class="menu-section-title">
    Seasons
  </div>
  <% for season in @all_seasons %>
    <div class="league_menu_item">
      <%= link_to season.name, league_season_path(season.league, season) %>
      <% if current_user.admin? season.league %>
        <%= link_to edit_league_season_path(season.league, season),
                    class: 'admin_menu_button' do %>
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</section>
<section id="instructions_button" class="menu_link">
  <a>
    <header>
      <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
      <span class="menu_label">Instructions</span>
    </header>
  </a>
</section>
<section id="sign_out_button" class="menu_link">
  <%= link_to destroy_user_session_path, method: :delete do %>
    <header>
      <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
      <span class="menu_label">Sign out</span>
    </header>
  <% end %>
</section>

app/views/common/nav_bar.html.erb
<nav id="site_nav" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a id="menu_button">
            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
          </a>
        </li>
      </ul>
    <% end %>
    <%= link_to 'BallsApp', root_path, class: 'navbar-brand' %>
  </div>
</nav>

app/views/common/spinner.html.erb
<div id="spinner_canvas"></div>

app/views/common/user_entrance.html.erb
<div id="user_entrance">
  <ul class="nav nav-tabs">
    <li id="sign_up_button" role="presentation" class="active">
      <a>Sign Up</a>
    </li>
    <li id="log_in_button" role="presentation" >
      <a>Log In</a>
    </li>
  </ul>
  <div class="well">
    <div id="sign_up_pane">
      <%= render 'devise/registrations/new' %>
    </div>
    <div id="log_in_pane" hidden=true>
      <%= render 'devise/sessions/new' %>
    </div>
  </div>
</div>